[package]
name = "bridger"
version = "0.1.0"
edition = "2021"
[workspace]
members = [ "armparser", "asm-inst"]
[dependencies]
armparser = { path = "armparser" }
asm-inst = { path = "asm-inst" }
either = "1.14.0"
phf = "0.11.3"
smallvec = "1.14.0"
